(()=>{"use strict";
const $=id=>document.getElementById(id),canvas=$("gameCanvas"),ctx=canvas.getContext("2d"),area=$("gameArea"),start=$("startOverlay"),countdown=$("countdownOverlay"),countdownValue=$("countdownValue"),pauseOverlay=$("pauseOverlay"),gameOver=$("gameOverOverlay"),pauseBtn=$("pauseButton"),soundBtn=$("soundButton"),scoreEl=$("scoreValue"),quartzEl=$("quartzValue"),bestEl=$("bestValue"),outsideBest=$("outsideBest"),outsideLevel=$("outsideLevel"),finalScore=$("finalScore"),finalBest=$("finalBest"),finalQuartz=$("finalQuartz"),newRecord=$("newRecord"),message=$("gameOverMessage");
const KEY="dinoCupMeteoritoRunBest",G=2100,BASE=430,MAX=920,GROUND=.79;
const state={mode:"idle",score:0,best:+localStorage.getItem(KEY)||0,level:1,speed:BASE,time:0,last:0,obsTimer:0,nextObs:1.2,rewardTimer:0,nextReward:2.7,sound:false,obstacles:[],rewards:[],particles:[],stars:[],raf:0,audio:null,quarzos:0};
const player={x:120,y:0,w:66,h:70,vy:0,grounded:true,frame:0};
const qLogo=new Image();qLogo.decoding="async";qLogo.src="https://www.quartzsales.com/images/q-02.svg";
const messages=["Ese meteorito tenía nombre y apellido.","La extinción llegó antes de tiempo.","Faltó reflejo jurásico.","El Cretácico no perdona.","Sobreviviste menos que el Wi-Fi del Kahoot."];
const rnd=(a,b)=>Math.random()*(b-a)+a,fmt=n=>Math.floor(Math.max(0,n)).toString().padStart(6,"0"),ground=()=>area.clientHeight*GROUND,hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function show(el,on){el.classList.toggle("is-visible",on);el.setAttribute("aria-hidden",on?"false":"true")}
function resize(){const r=area.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;canvas.style.width=r.width+"px";canvas.style.height=r.height+"px";ctx.setTransform(d,0,0,d,0,0);player.x=Math.max(70,r.width*(r.width<600?.18:.14));player.w=r.width<600?54:66;player.h=r.width<600?58:70;if(state.mode==="idle")player.y=ground()-player.h;state.stars=Array.from({length:Math.max(35,Math.floor(r.width/18))},(_,i)=>({x:i*97%r.width,y:30+i*53%(r.height*.5),a:.2+(i%7)*.08,s:1+i%3}));draw()}
function reset(){Object.assign(state,{score:0,level:1,speed:BASE,time:0,obsTimer:0,nextObs:1.2,rewardTimer:0,nextReward:rnd(2.2,3.7),obstacles:[],rewards:[],particles:[],quarzos:0});player.y=ground()-player.h;player.vy=0;player.grounded=true;player.frame=0;hud()}
async function begin(){if(["playing","countdown"].includes(state.mode))return;reset();state.mode="countdown";show(start,false);show(gameOver,false);show(pauseOverlay,false);show(countdown,true);pauseBtn.disabled=true;for(const v of["3","2","1","RUN_"]){countdownValue.textContent=v;tone(v==="RUN_"?650:350,.08);await new Promise(r=>setTimeout(r,v==="RUN_"?450:600))}show(countdown,false);state.mode="playing";pauseBtn.disabled=false;state.last=performance.now();cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop)}
function loop(t){if(state.mode!=="playing")return;const dt=Math.min((t-state.last)/1000,.032);state.last=t;update(dt);draw();state.raf=requestAnimationFrame(loop)}
function update(dt){state.time+=dt;state.score+=dt*(72+state.speed*.09);state.level=1+Math.floor(state.score/650);state.speed=Math.min(MAX,BASE+state.time*13+state.level*5);state.obsTimer+=dt;state.rewardTimer+=dt;if(state.obsTimer>state.nextObs){spawnMeteor();state.obsTimer=0;state.nextObs=Math.max(.68,1.5-state.time/120)+Math.random()*.45}if(state.rewardTimer>state.nextReward){spawnQuartz();state.rewardTimer=0;state.nextReward=rnd(2.3,4.2)}player.vy+=G*dt;player.y+=player.vy*dt;const floor=ground()-player.h;if(player.y>=floor){player.y=floor;player.vy=0;player.grounded=true;player.frame=(player.frame+dt*6.5*(state.speed/BASE))%4;if(Math.random()<dt*8)burst(player.x+player.w*.25,ground()-3,1,[Math.random()>.5?"#15d9ff":"#8347ff"])}else player.grounded=false;for(const o of state.obstacles){o.x-=state.speed*dt;o.r+=o.rs*dt;if(!o.passed&&o.x+o.w<player.x){o.passed=true;state.score+=35;tone(720,.03)}}for(const q of state.rewards){q.x-=state.speed*dt;q.phase+=dt*4}state.obstacles=state.obstacles.filter(o=>o.x+o.w>-70);state.rewards=state.rewards.filter(q=>!q.got&&q.x+q.w>-70);for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=420*dt}state.particles=state.particles.filter(p=>p.life>0);hud();collisions()}
function spawnMeteor(){const mobile=area.clientWidth<600,large=Math.random()<Math.min(.45,.18+state.time/160),size=large?rnd(mobile?48:58,mobile?66:84):rnd(mobile?30:38,mobile?43:55);state.obstacles.push({x:area.clientWidth+size,y:ground()-size*.76,w:size,h:size*.76,r:0,rs:rnd(-1.2,1.2),passed:false})}
function spawnQuartz(){const size=area.clientWidth<600?38:46;state.rewards.push({x:area.clientWidth+size+rnd(30,120),y:rnd(ground()-player.h*2.25,ground()-player.h*1.15),w:size,h:size,phase:rnd(0,Math.PI*2),got:false})}
function jump(){if(state.mode==="paused")return resume();if(state.mode!=="playing"||!player.grounded)return;player.vy=-(area.clientWidth<600?850:900);player.grounded=false;burst(player.x+20,ground()-4,8,["#15d9ff","#8347ff"]);tone(235,.08)}
function collisions(){const a={x:player.x+player.w*.2,y:player.y+player.h*.15,w:player.w*.6,h:player.h*.72};for(const q of state.rewards){if(hit(a,{x:q.x+q.w*.12,y:q.y+q.h*.12,w:q.w*.76,h:q.h*.76})){q.got=true;state.quarzos++;state.score+=150;burst(q.x+q.w/2,q.y+q.h/2,18,["#b8ff3d","#15d9ff","#fff"]);pop(q);tone(840,.08)}}for(const o of state.obstacles){if(hit(a,{x:o.x+o.w*.16,y:o.y+o.h*.13,w:o.w*.68,h:o.h*.74})){end();break}}}
function pop(q){const el=document.createElement("span");el.className="quartz-pop";el.textContent="+150";el.style.left=q.x+q.w/2+"px";el.style.top=q.y+"px";area.appendChild(el);setTimeout(()=>el.remove(),720)}
function end(){if(state.mode!=="playing")return;state.mode="gameover";cancelAnimationFrame(state.raf);burst(player.x+player.w/2,player.y+player.h/2,32,["#15d9ff","#ff35c7","#ffd33d","#8347ff"]);const score=Math.floor(state.score),record=score>state.best;if(record){state.best=score;localStorage.setItem(KEY,state.best)}finalScore.textContent=fmt(score);finalQuartz.textContent=String(state.quarzos).padStart(2,"0");finalBest.textContent=fmt(state.best);newRecord.hidden=!record;message.textContent=messages[Math.floor(Math.random()*messages.length)];hud();draw();setTimeout(()=>show(gameOver,true),350)}
function pause(){if(state.mode!=="playing")return;state.mode="paused";cancelAnimationFrame(state.raf);show(pauseOverlay,true);pauseBtn.classList.add("is-paused")}
function resume(){if(state.mode!=="paused")return;state.mode="playing";show(pauseOverlay,false);pauseBtn.classList.remove("is-paused");state.last=performance.now();state.raf=requestAnimationFrame(loop)}
function hud(){scoreEl.textContent=fmt(state.score);quartzEl.textContent=String(state.quarzos).padStart(2,"0");bestEl.textContent=outsideBest.textContent=fmt(state.best);outsideLevel.textContent=state.best>=7500?"JOHN HAMMOND":state.best>=5000?"ALAN GRANT":state.best>=3000?"IAN MALCOLM":state.best>=1500?"ELLIE SATTLER":state.best>=600?"LEX MURPHY":"TIM MURPHY"}
function burst(x,y,n,colors){for(let i=0;i<n;i++)state.particles.push({x,y,vx:rnd(-260,260),vy:rnd(-360,50),life:rnd(.3,.9),max:.9,size:rnd(2,8),c:colors[i%colors.length]})}
function draw(){const w=area.clientWidth,h=area.clientHeight,g=ground();let grd=ctx.createLinearGradient(0,0,0,h);grd.addColorStop(0,"#050515");grd.addColorStop(.5,"#090727");grd.addColorStop(1,"#160833");ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);sun(w,h);for(const s of state.stars){ctx.fillStyle=`rgba(190,233,255,${s.a})`;ctx.fillRect((s.x-state.time*state.speed*.03+w)%w,s.y,s.s,s.s)}ctx.strokeStyle="rgba(21,217,255,.12)";for(let i=-18;i<=18;i++){ctx.beginPath();ctx.moveTo(w/2+i*4,g);ctx.lineTo(w/2+i*w/18,h);ctx.stroke()}const off=(state.time*state.speed*.008)%1;for(let i=0;i<18;i++){const t=((i+off)%18)/18,y=g+(h-g)*t**1.8;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.shadowBlur=16;ctx.shadowColor="#15d9ff";ctx.strokeStyle="#15d9ff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,g);ctx.lineTo(w,g);ctx.stroke();ctx.shadowBlur=0;const dash=(state.time*state.speed*1.1)%130;for(let x=-dash;x<w+130;x+=130){ctx.strokeStyle="rgba(21,217,255,.28)";ctx.beginPath();ctx.moveTo(x,g+28);ctx.lineTo(x+48,g+28);ctx.stroke()}dino();for(const q of state.rewards)quartz(q);for(const o of state.obstacles)meteor(o);for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1}
function sun(w,h){const x=w*.76,y=h*.36,r=Math.min(w,h)*.1;ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();const g=ctx.createLinearGradient(0,y-r,0,y+r);g.addColorStop(0,"#ffd33d");g.addColorStop(.5,"#ff7547");g.addColorStop(1,"#ff35c7");ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.fillStyle="#090727";for(let i=0;i<7;i++)ctx.fillRect(x-r,y+r*.05+i*r*.19,r*2,r*(.045+i*.012));ctx.restore()}
function dino(){const phase=player.frame,bob=player.grounded?Math.sin(phase*Math.PI)*1.2:0,push=player.grounded?Math.cos(phase*Math.PI*.5)*.6:0,x=player.x+push,y=player.y+bob,p=player.w/18,R=(a,b,c,d,col)=>{ctx.fillStyle=col;ctx.fillRect(x+a*p,y+b*p,c*p,d*p)};ctx.shadowBlur=18;ctx.shadowColor="#15d9ff";const tail=Math.floor(phase)%2;R(0,8+tail,6,2,"#15d9ff");R(4,6,7,3,"#15d9ff");R(7,5,7,7,"#15d9ff");R(12,2,5,5,"#15d9ff");R(15,4,3,2,"#15d9ff");R(8,9,5,3,"#8347ff");R(14,6,4,2,"#15d9ff");R(16,7,2,1,"#ff35c7");R(14,3,1,1,"#04040d");if(player.grounded&&Math.floor(phase)%2===0){R(7,12,2,5,"#15d9ff");R(5,16,5,2,"#15d9ff");R(12,12,2,2,"#15d9ff");R(13,13,4,2,"#15d9ff")}else if(player.grounded){R(8,12,2,2,"#15d9ff");R(5,13,4,2,"#15d9ff");R(12,12,2,5,"#15d9ff");R(12,16,5,2,"#15d9ff")}else{R(8,12,2,3,"#15d9ff");R(7,14,3,2,"#15d9ff");R(12,12,2,3,"#15d9ff");R(13,14,3,2,"#15d9ff")}ctx.shadowBlur=0}
function quartz(q){const bob=Math.sin(q.phase)*4,cx=q.x+q.w/2,cy=q.y+q.h/2+bob;ctx.save();ctx.translate(cx,cy);ctx.shadowBlur=24;ctx.shadowColor="#8347ff";const aura=ctx.createRadialGradient(0,0,2,0,0,q.w*.55);aura.addColorStop(0,"rgba(131,71,255,.34)");aura.addColorStop(1,"rgba(131,71,255,0)");ctx.fillStyle=aura;ctx.beginPath();ctx.arc(0,0,q.w*.55,0,Math.PI*2);ctx.fill();if(qLogo.complete&&qLogo.naturalWidth){ctx.save();ctx.filter="brightness(0) invert(1)";ctx.drawImage(qLogo,-q.w*.42,-q.h*.42,q.w*.84,q.h*.84);ctx.restore()}else{ctx.save();ctx.rotate(Math.PI/4);ctx.fillStyle="rgba(255,255,255,.12)";ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.fillRect(-q.w*.23,-q.w*.23,q.w*.46,q.w*.46);ctx.strokeRect(-q.w*.23,-q.w*.23,q.w*.46,q.w*.46);ctx.restore()}ctx.restore()}
function meteor(o){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.r);const r=o.w/2,g=ctx.createRadialGradient(-r*.2,-r*.25,r*.08,0,0,r);g.addColorStop(0,"#ffd05d");g.addColorStop(.3,"#ff7547");g.addColorStop(.7,"#d83575");g.addColorStop(1,"#7025b7");ctx.fillStyle=g;ctx.shadowBlur=22;ctx.shadowColor="#ff35c7";ctx.beginPath();for(let i=0;i<12;i++){const a=Math.PI*2*i/12,rr=r*(.8+(i%4)*.04),px=Math.cos(a)*rr,py=Math.sin(a)*rr*.78;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.restore()}
function tone(f,d){if(!state.sound)return;if(!state.audio)state.audio=new(window.AudioContext||window.webkitAudioContext)();const o=state.audio.createOscillator(),g=state.audio.createGain(),n=state.audio.currentTime;o.type="square";o.frequency.value=f;g.gain.value=.025;g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(state.audio.destination);o.start();o.stop(n+d)}
$("startButton").onclick=begin;$("restartButton").onclick=begin;$("resumeButton").onclick=resume;pauseBtn.onclick=()=>state.mode==="playing"?pause():resume();soundBtn.onclick=()=>{state.sound=!state.sound;soundBtn.setAttribute("aria-pressed",state.sound);tone(520,.08)};for(const el of[canvas,$("mobileJumpButton")])el.addEventListener("pointerdown",e=>{e.preventDefault();jump()});addEventListener("keydown",e=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();jump()}if(e.code==="Escape"||e.code==="KeyP"){e.preventDefault();state.mode==="playing"?pause():resume()}if(e.code==="Enter"&&(state.mode==="idle"||state.mode==="gameover"))begin()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")pause()});addEventListener("resize",resize);hud();resize()})();